version: '3.1'

services:

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sala
      MYSQL_ROOT_PASSWORD: root
    expose:
    - '3306'
    ports:
      - 3306:3306
    volumes:
      - /home/andres/docker/mysql-data/sala:/var/lib/mysql
